### ISSUE TITLE
Tracking: Add support for SPA's

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-browser-analyzer#37]
The current version of the app looks only at PageView data and does have support for SPA's. Creating a capability to toggle b/w SPA and general web application and saving that preference with the entity is purpose of this issue.

- [x] Query the PageView and BrowserInteraction events to determine a default mode
- [ ] Add a toggle feature to the page to transition b/w measurement methodologies
- [ ] Saving (and loading) that context via entity-scoped NerdStorage

This issue is a collaboration with @ShuJackson who prototyped this solution here: https://github.com/ShuJackson/nr1-browser-analyzer
